config/routes.rb
Pintapedia::Application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :words do
    resources :comments
  end

  root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :word
  attr_accessible :autor, :body
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth)

    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end

  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :autor, :description, :name
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  
  private
  
  def require_login_on_face
    unless loggin_in?
      flash[:error] = "Voce precisa logar com o Facebook"
      redirect_to "/auth/facebook/"
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def loggin_in?
    !!current_user
  end
  helper_method :current_user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @words = Word.find(params[:word_id])
    @comments = @words.comments
    @comment = @words.comments.build

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @words = Word.find(params[:word_id])
    @comment = @words.comments.create(params[:comment])
    
    redirect_to word_path(@words)
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_filter :require_login_on_face, :only => [:index]

  def index
    @word = Word.new
    @girias = Word.find(:all, :order => "created_at DESC", :limit => 5)
  end
  
  def show
    @words = Word.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @words }
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  def omniauth_failure
    redirect_to root_path
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @words = Word.paginate(:page => params[:page], :per_page => 5).order('id DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @words = Word.find(params[:id])
   

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @words }
    end
  end

  # GET /words/new
  # GET /words/new.json
  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @words }
      format.js
    end
  end

  # GET /words/1/edit
  def edit
    @words = Word.find(params[:id])
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to root_path, alert: 'Word was successfully created.' }
        format.json { render json: root_path, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @words = Word.find(params[:id])

    respond_to do |format|
      if @words.update_attributes(params[:word])
        format.html { redirect_to @words, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @words.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @words = Word.find(params[:id])
    @words.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/comments/_comentarios.html.erb
<p>
  <b>Nome:</b>
  <%= comentarios.autor %>
</p>
<p>
  <b>Falação:</b>
  <%= comentarios.body %>
</p>

<hr />

app/views/comments/_form.html.erb
<%= form_for([@words, @words.comments.build], :html => {:class => 'form-horizontal'}) do |f| %>
  <div class="field">
    <%= f.label :autor, "Nome" %>
    <% if current_user %>
      <%= f.text_field :autor, :value => current_user.name %>
    <% end %>

  </div>
  <div class="field">
    <%= f.label :body, "Comentario" %>
    <%= f.text_area :body, :rows => 4 %>
  </div>

  <div class="actions">
    <%= f.submit "Comentar" %>
  </div>


<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Autor</th>
    <th>Body</th>
    <th>Word</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.autor %></td>
    <td><%= comment.body %></td>
    <td><%= comment.word %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Autor:</b>
  <%= @comment.autor %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Word:</b>
  <%= @comment.word %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/_login.html.erb
<% if current_user %>

  <button class="btn btn-primary">Esse home entrou como <strong><%= current_user.name %></strong>!</button> 
  <br /><br />
  <%= link_to "Sair", signout_path, id: "sign_out", :class => 'btn btn-danger' %>
<% else %>
  <%= link_to "Entre com o usuário do Facebook", "/auth/facebook", id: "sign_in", :class => 'btn btn-primary' %>
<% end %>

app/views/home/index.html.erb
<div class="hero-unit">
  <h1>Pintapedia</h1>
  <p>Esse rolé aqui foi coisado pra mostra prus boy as giria que os boy fala ai...</p>

  <br /><small>Ai esse homi clica naquele rolé aqui d'baixo pra butar uma giria ai que esse ohm conhece...</small>
  <button id="opener"class="btn btn-block btn-primary">Cadastrar Giria</button><br />
  <div id="dialog" title="Giria" >
    <%= render "words/form", :object => @word %>
  </div>
<hr>
  <div class="row">
    <div class="span3">
      Recém Cadastrado <br />
      <% @girias.each do |word| %>
        <%= link_to word.name, word, :controller => 'home' %> <br />
        <small><%= word.autor %></small><br />
        <hr />
      <% end %>
    </div>
    <div class="span4">
      <blockquote class="pull-right">
        <h4>Clique aqui mermão pra ver as Girias</h4>
        <%= link_to "Todas as Girias", words_path, :class=> 'btn' %>
      </blockquote>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pintapedia</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
          <%= image_tag("logo.png", :class => "img-rounded",:size => "35x35") %>
          <%= link_to "Pintapedia", root_path, :class => 'brand' %>
      <div class="nav-collapse">
        <ul class="nav">
          <li></li>
        </ul>
      </div>
    </div>
  </div>
  
</div>
<div class="container">
  <div class="row">
    <div class="span10">
      <%= yield %>
    </div>
    <div class="span2">
      <h4>Entrem com o Facebook, para ficar mais divertido :)</h4>
      <%= render :partial => "home/login" %>
     </div>
  </div>
</div>

</body>
</html>

app/views/words/_form.html.erb
<%= form_for @word, :html => { :class => 'form-inline'} do |f| %>
  <br />
  <div class="control-group">
    <%= f.label :name,"Giria", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, "data-validation" => "validate_length length3-5", :class => 'input-medium',:size => 2,:placeholder => "Digite sua Giria" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description,"Descrição", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area',:rows => 3, :placeholder => "Digite o Significado" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :autor, :class => 'control-label' %>
    <div class="controls">
      <% if current_user %>
        <%= f.text_field :autor, :class => 'text_field',:value => current_user.name %>
      <% else %>
       <%= link_to "Entre com o usuário do Facebook", "/auth/facebook", id: "sign_in", :class => 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

  <center>
  <div class="form-actions">
    <%= f.submit "Cadastrar", :class => 'btn btn-primary' %>
  </div>
</center>
<% end %>

app/views/words/edit.html.erb
<%- model_class = Word -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/words/index.html.erb
<div class="page-header">
  <h1>Girias</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      
      <th>Giria</th>
      <th>Autor</th>

      <th><%=t '.actions', :default => t("helpers.Opções") %></th>
    </tr>
  </thead>
  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.name %></td>
        <td><%= word.autor %></td>

        <td>
          <%= link_to t('.show', :default => t("helpers.links.Mais Informações")),
                      word_path(word), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="pager">
  <%= will_paginate @words,:previous_label => "&laquo; Anterior", :next_label => "Proximo &raquo;" %>
</div>
<%= link_to t('.new', :default => t("helpers.links.Nova Giria")),
            new_word_path,
            :class => 'btn btn-primary' %>

app/views/words/new.html.erb
<div class="page-header">
  <h1>Giria</h1>
</div>
<%= render :partial => 'form' %>

app/views/words/show.html.erb
<div class="page-header">
  <h1>Giria</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Giria:</strong></dt>
  <dd><%= @words.name %></dd>
  <dt><strong>O Que quer dizer?</strong></dt>
  <dd><%= @words.description %></dd>
  <dt><strong>Autor:</strong></dt>
  <dd><%= @words.autor %></dd>
</dl>
<hr />
<h3>Adicionar Comentario</h3>

<%= render :partial => "comments/form" %>

<h3>Comentarios</h3>

<%= render :partial => "comments/comentarios", :collection => @words.comments %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.voltar")),
              root_path, :class => 'btn'  %>
</div>